/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sky_jni_jnicjava_TestCJavaJni */

#ifndef _Included_com_sky_jni_jnicjava_TestCJavaJni
#define _Included_com_sky_jni_jnicjava_TestCJavaJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sky_jni_jnicjava_TestCJavaJni
 * Method:    callBackAdd
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sky_jni_jnicjava_TestCJavaJni_callBackAdd
  (JNIEnv *, jobject);

/*
 * Class:     com_sky_jni_jnicjava_TestCJavaJni
 * Method:    callBackFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sky_jni_jnicjava_TestCJavaJni_callBackFromJava
  (JNIEnv *, jobject);

/*
 * Class:     com_sky_jni_jnicjava_TestCJavaJni
 * Method:    callPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sky_jni_jnicjava_TestCJavaJni_callPrintString
  (JNIEnv *, jobject);

/*
 * Class:     com_sky_jni_jnicjava_TestCJavaJni
 * Method:    callBackSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sky_jni_jnicjava_TestCJavaJni_callBackSayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_sky_jni_jnicjava_TestCJavaJni
 * Method:    callBackResultStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sky_jni_jnicjava_TestCJavaJni_callBackResultStr
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
